import { AppButton, AppInput, AppSelect, AppTextArea } from '../../../shared/components/MuiPrimitives'
import { useEffect, useMemo, type FormEvent } from 'react'
import { useShallow } from 'zustand/react/shallow'
import { ResponsiveModalForm } from '../../../components/ResponsiveModalForm'
import { formatMinorMoney, moneyInputStep } from '../../../shared/lib/money'
import { useAdminCompetitionsStore, type PlayerForm, type TeamForm, type TournamentForm } from '../../../stores/admin/useAdminCompetitionsStore'

const statuses = ['inscripciones_abiertas', 'en_progreso', 'finalizado', 'cancelado'] as const
export function AdminCompetitionsPage() {
  const s = useAdminCompetitionsStore(useShallow((state) => state))
  useEffect(() => { void s.load() }, [s.load])
  const tournaments = useMemo(() => { const term = s.search.toLowerCase(); return s.tournaments.filter((item) => !term || `${item.nombre} ${item.negocios?.nombre} ${item.deportes?.nombre}`.toLowerCase().includes(term)) }, [s.search, s.tournaments])
  const teams = useMemo(() => { const term = s.search.toLowerCase(); return s.teams.filter((item) => !term || `${item.nombre} ${item.usuarios?.nombre} ${item.ciudad}`.toLowerCase().includes(term)) }, [s.search, s.teams])
  const submitTournament = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); void s.saveTournament() }, submitTeam = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); void s.saveTeam() }, submitPlayer = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); void s.addPlayer() }, submitAssignment = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); void s.assignTeam() }
  return <main className="page-container"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="section-kicker">Operacion deportiva</p><h1 className="page-title">Competiciones</h1><p className="mt-2 text-zinc-600">Gestiona torneos, equipos, plantillas e inscripciones.</p></div><AppButton className="primary-button" onClick={s.tab === 'tournaments' ? s.createTournament : s.createTeam}>{s.tab === 'tournaments' ? 'Nuevo torneo' : 'Nuevo equipo'}</AppButton></div><div className="mt-7 flex flex-col gap-3 border-y bg-white p-3 md:flex-row"><div className="grid grid-cols-2 gap-1 bg-zinc-100 p-1"><Tab active={s.tab === 'tournaments'} onClick={() => s.setTab('tournaments')}>Torneos</Tab><Tab active={s.tab === 'teams'} onClick={() => s.setTab('teams')}>Equipos</Tab></div><AppInput className="field flex-1" type="search" placeholder="Buscar" value={s.search} onChange={(event) => s.setSearch(event.target.value)} /></div>{s.error && !s.tournamentOpen && !s.teamOpen && !s.rosterTeam && !s.assignmentTournament && <p className="form-error mt-5">{s.error}</p>}{s.message && <p className="form-success mt-5">{s.message}</p>}
    {s.tab === 'tournaments' ? <section className="mt-6 grid gap-4 xl:grid-cols-2">{tournaments.map((item) => <Card key={item.id}><div className="flex justify-between gap-3"><div><p className="text-xs font-bold uppercase text-emerald-700">{item.deportes?.nombre} · {item.negocios?.nombre}</p><h2 className="mt-1 text-lg font-black">{item.nombre}</h2><p className="text-sm text-zinc-500">{item.fecha_inicio} a {item.fecha_fin}</p></div><span className="status-badge h-fit">{item.estado.replaceAll('_', ' ')}</span></div><div className="mt-4 grid grid-cols-2 border-y py-3"><span>{item.inscripciones_torneo.length} / {item.max_equipos} equipos</span><strong>{formatMinorMoney(item.costo_inscripcion_minor, item.moneda)}</strong></div><Actions><AppButton className="secondary-button" onClick={() => s.editTournament(item)}>Editar</AppButton><AppButton className="secondary-button" onClick={() => s.openAssignment(item)}>Asignar equipos</AppButton><AppButton className="secondary-button text-red-700" onClick={() => window.confirm(`Eliminar ${item.nombre}?`) && void s.removeTournament(item)}>Eliminar</AppButton></Actions></Card>)}</section> : <section className="mt-6 grid gap-4 xl:grid-cols-2">{teams.map((item) => <Card key={item.id}><p className="text-xs font-bold uppercase text-blue-700">{item.ciudad}, {item.pais_codigo}</p><h2 className="mt-1 text-lg font-black">{item.nombre}</h2><p className="text-sm text-zinc-500">Capitan: {item.usuarios?.nombre} · {item.jugadores_equipo.length} jugadores</p><Actions><AppButton className="secondary-button" onClick={() => s.editTeam(item)}>Editar</AppButton><AppButton className="secondary-button" onClick={() => s.openRoster(item)}>Plantilla</AppButton><AppButton className="secondary-button text-red-700" onClick={() => window.confirm(`Eliminar ${item.nombre}?`) && void s.removeTeam(item)}>Eliminar</AppButton></Actions></Card>)}</section>}
    {s.tournamentOpen && <ResponsiveModalForm title={s.editingTournament ? 'Editar torneo' : 'Nuevo torneo'} kicker="Competicion" onClose={s.closeTournament} onSubmit={submitTournament} actions={<><AppButton className="secondary-button" type="button" onClick={s.closeTournament}>Cancelar</AppButton><AppButton className="primary-button" disabled={s.saving}>Guardar torneo</AppButton></>}><div className="responsive-modal-grid"><Field label="Negocio"><AppSelect className="field" value={s.tournamentForm.businessId} onChange={(event) => s.selectTournamentBusiness(event.target.value)}>{s.businesses.map((item) => <option key={item.id} value={item.id}>{item.nombre}</option>)}</AppSelect></Field><Field label="Deporte"><AppSelect className="field" value={s.tournamentForm.sportId} onChange={(event) => s.setTournamentField('sportId', event.target.value)}>{s.sports.map((item) => <option key={item.id} value={item.id}>{item.nombre}</option>)}</AppSelect></Field><TournamentInput field="name" label="Nombre" form={s.tournamentForm} setField={s.setTournamentField} wide /><TournamentInput field="start" label="Fecha inicial" form={s.tournamentForm} setField={s.setTournamentField} type="date" /><TournamentInput field="end" label="Fecha final" form={s.tournamentForm} setField={s.setTournamentField} type="date" /><TournamentInput field="registrationsOpen" label="Abren inscripciones" form={s.tournamentForm} setField={s.setTournamentField} type="datetime-local" /><TournamentInput field="registrationsClose" label="Cierran inscripciones" form={s.tournamentForm} setField={s.setTournamentField} type="datetime-local" /><TournamentInput field="maxTeams" label="Maximo equipos" form={s.tournamentForm} setField={s.setTournamentField} type="number" /><TournamentInput field="maxPlayers" label="Jugadores por equipo" form={s.tournamentForm} setField={s.setTournamentField} type="number" /><Field label={`Inscripcion (${s.tournamentForm.currency})`}><AppInput className="field" type="number" step={moneyInputStep(s.tournamentForm.currency)} value={s.tournamentForm.fee} onChange={(event) => s.setTournamentField('fee', event.target.value)} /></Field><Field label="Estado"><AppSelect className="field" value={s.tournamentForm.status} onChange={(event) => s.setTournamentField('status', event.target.value as TournamentForm['status'])}>{statuses.map((item) => <option key={item}>{item}</option>)}</AppSelect></Field><Field label="Descripcion" wide><AppTextArea className="field min-h-24" value={s.tournamentForm.description} onChange={(event) => s.setTournamentField('description', event.target.value)} /></Field></div>{s.error && <p className="form-error mt-4">{s.error}</p>}</ResponsiveModalForm>}
    {s.teamOpen && <ResponsiveModalForm title={s.editingTeam ? 'Editar equipo' : 'Nuevo equipo'} kicker="Equipo" onClose={s.closeTeam} onSubmit={submitTeam} actions={<><AppButton className="secondary-button" type="button" onClick={s.closeTeam}>Cancelar</AppButton><AppButton className="primary-button" disabled={s.saving}>Guardar equipo</AppButton></>}><div className="responsive-modal-grid"><TeamInput field="name" label="Nombre" form={s.teamForm} setField={s.setTeamField} /><Field label="Capitan"><AppSelect className="field" value={s.teamForm.captainId} onChange={(event) => s.setTeamField('captainId', event.target.value)}>{s.users.map((item) => <option key={item.id} value={item.id}>{item.nombre}</option>)}</AppSelect></Field><Field label="Pais"><AppSelect className="field" value={s.teamForm.countryCode} onChange={(event) => s.setTeamField('countryCode', event.target.value)}>{s.countries.map((item) => <option key={item.id} value={item.codigo_iso2}>{item.nombre}</option>)}</AppSelect></Field><TeamInput field="department" label="Departamento" form={s.teamForm} setField={s.setTeamField} /><TeamInput field="city" label="Ciudad" form={s.teamForm} setField={s.setTeamField} /><TeamInput field="logoUrl" label="URL del logo" form={s.teamForm} setField={s.setTeamField} /></div>{s.error && <p className="form-error mt-4">{s.error}</p>}</ResponsiveModalForm>}
    {s.rosterTeam && <ResponsiveModalForm title={`Plantilla · ${s.rosterTeam.nombre}`} kicker={`${s.rosterTeam.jugadores_equipo.length} jugadores`} onClose={s.closeRoster} onSubmit={submitPlayer} actions={<><AppButton className="secondary-button" type="button" onClick={s.closeRoster}>Cerrar</AppButton><AppButton className="primary-button" disabled={s.saving}>Agregar jugador</AppButton></>}><div className="divide-y border-y">{s.rosterTeam.jugadores_equipo.map((item) => <div className="flex justify-between py-3" key={item.id}><div><p className="font-bold">{item.nombre}</p><p className="text-xs text-zinc-500">{item.identificacion}</p></div><AppButton className="secondary-button" type="button" onClick={() => void s.removePlayer(item.id)}>Quitar</AppButton></div>)}</div><div className="responsive-modal-grid mt-5"><PlayerInput field="name" label="Nombre" form={s.playerForm} setField={s.setPlayerField} /><PlayerInput field="identification" label="Identificacion" form={s.playerForm} setField={s.setPlayerField} /><PlayerInput field="phone" label="Telefono" form={s.playerForm} setField={s.setPlayerField} /><PlayerInput field="number" label="Numero" form={s.playerForm} setField={s.setPlayerField} type="number" /></div>{s.error && <p className="form-error mt-4">{s.error}</p>}</ResponsiveModalForm>}
    {s.assignmentTournament && <ResponsiveModalForm title="Asignar equipos" kicker={s.assignmentTournament.nombre} size="sm" onClose={s.closeAssignment} onSubmit={submitAssignment} actions={<><AppButton className="secondary-button" type="button" onClick={s.closeAssignment}>Cerrar</AppButton><AppButton className="primary-button" disabled={!s.assignmentTeamId || s.saving}>Asignar</AppButton></>}><div className="divide-y border-y">{s.assignmentTournament.inscripciones_torneo.map((item) => <div className="flex justify-between py-3" key={item.id}><strong>{item.equipos?.nombre}</strong><AppButton className="secondary-button" type="button" onClick={() => void s.unassignTeam(item.id)}>Retirar</AppButton></div>)}</div><Field label="Equipo disponible"><AppSelect className="field" value={s.assignmentTeamId} onChange={(event) => s.setAssignmentTeamId(event.target.value)}><option value="">Seleccionar</option>{s.teams.filter((team) => !s.assignmentTournament!.inscripciones_torneo.some((item) => item.equipo_id === team.id)).map((team) => <option key={team.id} value={team.id}>{team.nombre}</option>)}</AppSelect></Field></ResponsiveModalForm>}
  </main>
}
function Card({ children }: { children: React.ReactNode }) { return <article className="rounded-md border border-zinc-200 bg-white p-5">{children}</article> }
function Actions({ children }: { children: React.ReactNode }) { return <div className="mt-4 flex flex-wrap gap-2 border-t pt-4">{children}</div> }
function Tab({ active, onClick, children }: { active: boolean; onClick: () => void; children: React.ReactNode }) { return <AppButton className={`px-4 py-2 text-sm font-bold ${active ? 'bg-white shadow-sm' : 'text-zinc-500'}`} onClick={onClick}>{children}</AppButton> }
function Field({ label, wide = false, children }: { label: string; wide?: boolean; children: React.ReactNode }) { return <label className={`min-w-0 text-sm font-semibold ${wide ? 'md:col-span-2' : ''}`}>{label}<span className="mt-1.5 block">{children}</span></label> }
function TournamentInput({ field, label, form, setField, type = 'text', wide = false }: { field: 'name' | 'start' | 'end' | 'registrationsOpen' | 'registrationsClose' | 'maxTeams' | 'maxPlayers'; label: string; form: TournamentForm; setField: <K extends keyof TournamentForm>(field: K, value: TournamentForm[K]) => void; type?: string; wide?: boolean }) { return <Field label={label} wide={wide}><AppInput className="field" required value={form[field]} type={type} onChange={(event) => setField(field, event.target.value)} /></Field> }
function TeamInput({ field, label, form, setField }: { field: 'name' | 'department' | 'city' | 'logoUrl'; label: string; form: TeamForm; setField: <K extends keyof TeamForm>(field: K, value: TeamForm[K]) => void }) { return <Field label={label}><AppInput className="field" required={field !== 'logoUrl'} value={form[field]} onChange={(event) => setField(field, event.target.value)} /></Field> }
function PlayerInput({ field, label, form, setField, type = 'text' }: { field: keyof PlayerForm; label: string; form: PlayerForm; setField: <K extends keyof PlayerForm>(field: K, value: PlayerForm[K]) => void; type?: string }) { return <Field label={label}><AppInput className="field" required={field === 'name' || field === 'identification'} type={type} value={form[field]} onChange={(event) => setField(field, event.target.value)} /></Field> }
