import { AppButton, AppInput, AppSelect, AppTextArea } from '../../../shared/components/MuiPrimitives'
import { useEffect, useMemo, type FormEvent } from 'react'
import { Link } from 'react-router-dom'
import { useShallow } from 'zustand/react/shallow'
import { ResponsiveModalForm } from '../../../components/ResponsiveModalForm'
import { useAdminSupportStore } from '../../../stores/admin/useAdminSupportStore'
import { useAuthStore } from '../../../stores/useAuthStore'

const statuses = ['abierto', 'en_progreso', 'esperando_negocio', 'resuelto', 'cerrado']
const priorities = ['baja', 'media', 'alta', 'critica']

export function AdminSupportPage() {
  const currentUser = useAuthStore((state) => state.user)
  const state = useAdminSupportStore(useShallow((store) => store))

  useEffect(() => { void state.load() }, [state.load])

  const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); if (currentUser) void state.save(currentUser.id) }

  const filteredCases = useMemo(() => { const term = state.search.trim().toLocaleLowerCase('es'); return state.cases.filter((item) => !term || `${item.titulo} ${item.negocios?.nombre ?? ''} ${item.estado} ${item.prioridad}`.toLocaleLowerCase('es').includes(term)) }, [state.cases, state.search])
  const filteredHealth = useMemo(() => { const term = state.search.trim().toLocaleLowerCase('es'); return state.healthRows.filter((item) => !term || `${item.business.nombre} ${item.business.ciudad} ${item.subscription}`.toLocaleLowerCase('es').includes(term)) }, [state.healthRows, state.search])
  const filteredAudits = useMemo(() => { const term = state.search.trim().toLocaleLowerCase('es'); return state.audits.filter((item) => !term || `${item.tabla} ${item.accion} ${item.usuarios?.nombre ?? ''} ${item.negocios?.nombre ?? ''}`.toLocaleLowerCase('es').includes(term)) }, [state.audits, state.search])

  return <main className="page-container">
    <div className="flex flex-wrap items-end justify-between gap-4"><div><p className="section-kicker">Centro de control</p><h1 className="page-title">Soporte y auditoria</h1><p className="mt-2 text-zinc-600">Atiende negocios con contexto operativo completo y trazabilidad administrativa.</p></div>{state.tab === 'cases' && <AppButton className="primary-button" onClick={() => state.create(currentUser?.id ?? '')}>Nuevo caso</AppButton>}</div>
    <div className="mt-7 flex flex-col gap-3 border-y border-zinc-200 bg-white p-3 lg:flex-row lg:items-center"><div className="grid grid-cols-3 gap-1 rounded-md bg-zinc-100 p-1"><TabButton active={state.tab === 'cases'} onClick={() => state.setTab('cases')}>Casos</TabButton><TabButton active={state.tab === 'health'} onClick={() => state.setTab('health')}>Diagnostico</TabButton><TabButton active={state.tab === 'audit'} onClick={() => state.setTab('audit')}>Auditoria</TabButton></div><AppInput className="field min-w-0 flex-1" type="search" placeholder="Buscar negocio, estado, tabla o responsable" value={state.search} onChange={(event) => state.setSearch(event.target.value)} /></div>
    {state.error && !state.open && <p className="form-error mt-5">{state.error}</p>}{state.message && <p className="form-success mt-5">{state.message}</p>}

    {state.tab === 'cases' && <section className="mt-6 grid gap-4 xl:grid-cols-2">{filteredCases.map((item) => <article className="rounded-md border border-zinc-200 bg-white p-5" key={item.id}><div className="flex items-start justify-between gap-3"><div className="min-w-0"><p className="text-xs font-bold uppercase text-emerald-700">{item.negocios?.nombre}</p><h2 className="mt-1 truncate text-lg font-black">{item.titulo}</h2></div><span className={`status-badge shrink-0 ${item.estado === 'resuelto' || item.estado === 'cerrado' ? 'status-active' : ''}`}>{item.estado.replaceAll('_', ' ')}</span></div><p className="mt-3 line-clamp-2 text-sm text-zinc-600">{item.descripcion}</p><div className="mt-4 flex flex-wrap gap-x-5 gap-y-2 border-t border-zinc-100 pt-4 text-xs text-zinc-500"><span>Prioridad: <strong className="text-zinc-800">{item.prioridad}</strong></span><span>Asignado: <strong className="text-zinc-800">{item.asignado?.nombre ?? 'Sin asignar'}</strong></span><span>{new Date(item.creado_en).toLocaleString('es-CO')}</span></div><div className="mt-4 flex gap-2"><AppButton className="secondary-button" onClick={() => state.edit(item)}>Atender</AppButton><AppButton className="secondary-button text-red-700" onClick={() => { if (window.confirm(`Eliminar el caso ${item.titulo}? La accion quedara en auditoria.`)) void state.remove(item) }}>Eliminar</AppButton></div></article>)}{filteredCases.length === 0 && <Empty text="No hay casos de soporte que coincidan." />}</section>}

    {state.tab === 'health' && <section className="mt-6 overflow-x-auto border-y border-zinc-200 bg-white"><div className="min-w-[850px]"><div className="support-health-grid bg-zinc-50 px-4 py-3 text-xs font-bold uppercase text-zinc-500"><span>Negocio</span><span>Estado</span><span>Suscripcion</span><span>Actividad</span><span>Accion</span></div>{filteredHealth.map((item) => <article className="support-health-grid items-center border-t border-zinc-200 px-4 py-4" key={item.business.id}><div><p className="font-bold">{item.business.nombre}</p><p className="text-xs text-zinc-500">{item.business.ciudad}, {item.business.pais_codigo}</p></div><span className={`status-badge w-fit ${item.business.estado === 'activo' ? 'status-active' : ''}`}>{item.business.estado}</span><p className="text-sm font-semibold">{item.subscription.replaceAll('_', ' ')}</p><p className="text-sm text-zinc-600">{item.courts} canchas · {item.reservations} reservas · {item.tournaments} torneos</p><div className="flex gap-2"><AppButton className="secondary-button" onClick={() => state.createForBusiness(item.business.id, currentUser?.id ?? '')}>Abrir caso</AppButton><Link className="secondary-button inline-flex" to="/admin/negocios">Gestionar</Link></div></article>)}</div></section>}

    {state.tab === 'audit' && <section className="mt-6 overflow-x-auto border-y border-zinc-200 bg-white"><div className="min-w-[850px]"><div className="support-audit-grid bg-zinc-50 px-4 py-3 text-xs font-bold uppercase text-zinc-500"><span>Fecha</span><span>Administrador</span><span>Accion</span><span>Entidad</span><span>Negocio</span></div>{filteredAudits.map((item) => <article className="support-audit-grid items-center border-t border-zinc-200 px-4 py-4" key={item.id}><p className="text-sm">{new Date(item.creado_en).toLocaleString('es-CO')}</p><p className="font-semibold">{item.usuarios?.nombre}</p><span className="status-badge w-fit">{item.accion}</span><div><p className="font-semibold">{item.tabla}</p><p className="max-w-48 truncate text-xs text-zinc-500">{item.registro_id}</p></div><p className="text-sm text-zinc-600">{item.negocios?.nombre ?? 'No asociado'}</p></article>)}</div></section>}

    {state.open && <ResponsiveModalForm title={state.editing ? 'Atender caso' : 'Nuevo caso'} kicker="Soporte tecnico" onClose={state.close} onSubmit={submit} actions={<><AppButton className="secondary-button" type="button" onClick={state.close}>Cancelar</AppButton><AppButton className="primary-button" disabled={state.saving}>{state.saving ? 'Guardando...' : state.editing ? 'Guardar seguimiento' : 'Crear caso'}</AppButton></>}><div className="responsive-modal-grid"><Field label="Negocio" wide><AppSelect className="field" required value={state.form.businessId} onChange={(event) => state.setField('businessId', event.target.value)}>{state.businesses.map((item) => <option key={item.id} value={item.id}>{item.nombre} · {item.ciudad}</option>)}</AppSelect></Field><Field label="Titulo" wide><AppInput className="field" required minLength={3} value={state.form.title} onChange={(event) => state.setField('title', event.target.value)} /></Field><Field label="Prioridad"><AppSelect className="field" value={state.form.priority} onChange={(event) => state.setField('priority', event.target.value)}>{priorities.map((item) => <option key={item}>{item}</option>)}</AppSelect></Field><Field label="Estado"><AppSelect className="field" value={state.form.status} onChange={(event) => state.setField('status', event.target.value)}>{statuses.map((item) => <option key={item} value={item}>{item.replaceAll('_', ' ')}</option>)}</AppSelect></Field><Field label="Asignado a" wide><AppSelect className="field" value={state.form.assigneeId} onChange={(event) => state.setField('assigneeId', event.target.value)}><option value="">Sin asignar</option>{state.admins.map((item) => <option key={item.id} value={item.id}>{item.nombre} · {item.email}</option>)}</AppSelect></Field><Field label="Descripcion" wide><AppTextArea className="field min-h-28 resize-y" required minLength={3} value={state.form.description} onChange={(event) => state.setField('description', event.target.value)} /></Field><Field label="Resolucion" wide><AppTextArea className="field min-h-24 resize-y" placeholder="Diagnostico, acciones realizadas y resultado" value={state.form.resolution} onChange={(event) => state.setField('resolution', event.target.value)} /></Field></div>{state.error && <p className="form-error mt-4">{state.error}</p>}</ResponsiveModalForm>}
  </main>
}

function TabButton({ active, onClick, children }: { active: boolean; onClick: () => void; children: React.ReactNode }) { return <AppButton className={`px-3 py-2 text-sm font-bold ${active ? 'rounded bg-white shadow-sm' : 'text-zinc-500'}`} onClick={onClick}>{children}</AppButton> }
function Field({ label, wide = false, children }: { label: string; wide?: boolean; children: React.ReactNode }) { return <label className={`min-w-0 text-sm font-semibold text-zinc-700 ${wide ? 'md:col-span-2' : ''}`}>{label}<span className="mt-1.5 block min-w-0">{children}</span></label> }
function Empty({ text }: { text: string }) { return <div className="rounded-md border border-dashed border-zinc-300 bg-white px-6 py-12 text-center text-sm text-zinc-500 xl:col-span-2">{text}</div> }
