import { create } from 'zustand'
import { adminRepository } from '../../services/repositories/adminRepository'
import type { Plan } from '../../services/supabase/tables'
import { majorToMinor, minorToMajor } from '../../shared/lib/money'

export type PlanForm = { name: string; description: string; limit: string; price: string; currency: string; active: boolean }
const emptyForm: PlanForm = { name: '', description: '', limit: '3', price: '29', currency: 'USD', active: true }
const slugify = (value: string) => value.normalize('NFD').replace(/[\u0300-\u036f]/g, '').toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '')
type State = { plans: Plan[]; editing: Plan | null; form: PlanForm; open: boolean; error: string; saving: boolean; load: () => Promise<void>; create: () => void; edit: (plan: Plan) => void; close: () => void; setField: <K extends keyof PlanForm>(field: K, value: PlanForm[K]) => void; save: () => Promise<void>; toggle: (plan: Plan) => Promise<void> }
export const useAdminPlansStore = create<State>((set, get) => ({ plans: [], editing: null, form: emptyForm, open: false, error: '', saving: false, load: async () => { try { set({ plans: await adminRepository.fetchPlans(), error: '' }) } catch (error) { set({ error: error instanceof Error ? error.message : 'No se pudieron cargar los planes.' }) } }, create: () => set({ editing: null, form: emptyForm, open: true, error: '' }), edit: (plan) => { const currency = plan.moneda_codigo ?? plan.moneda; set({ editing: plan, open: true, error: '', form: { name: plan.nombre, description: plan.descripcion ?? '', limit: String(plan.limite_canchas), price: String(minorToMajor(plan.precio_mensual_minor, currency)), currency, active: plan.activo } }) }, close: () => set({ open: false }), setField: (field, value) => set((state) => ({ form: { ...state.form, [field]: value } })), save: async () => { const { form, editing } = get(); const currency = form.currency.trim().toUpperCase(); set({ saving: true, error: '' }); try { await adminRepository.savePlan(editing?.id ?? null, { nombre: form.name.trim(), descripcion: form.description.trim() || null, limite_canchas: Number(form.limit), precio_mensual_minor: majorToMinor(form.price, currency), moneda: currency, moneda_codigo: currency, activo: form.active, slug: slugify(form.name) }); await get().load(); set({ saving: false, open: false }) } catch (error) { set({ saving: false, error: error instanceof Error ? error.message : 'No se pudo guardar el plan.' }) } }, toggle: async (plan) => { try { await adminRepository.updatePlan(plan.id, { activo: !plan.activo }); await get().load() } catch (error) { set({ error: error instanceof Error ? error.message : 'No se pudo actualizar el plan.' }) } } }))
