import { create } from 'zustand'
import { adminRepository } from '../../services/repositories/adminRepository'
import type { Deporte } from '../../services/supabase/tables'

export type SportForm = { name: string; slug: string; category: string; players: string; active: boolean }
const emptyForm: SportForm = { name: '', slug: '', category: '', players: '', active: true }
const slugify = (value: string) => value.normalize('NFD').replace(/[\u0300-\u036f]/g, '').toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '')
type State = { sports: Deporte[]; search: string; filtersOpen: boolean; statusFilter: 'all' | 'active' | 'inactive'; categoryFilter: string; editing: Deporte | null; form: SportForm; open: boolean; saving: boolean; error: string; message: string; load: () => Promise<void>; setSearch: (value: string) => void; toggleFilters: () => void; setStatusFilter: (value: State['statusFilter']) => void; setCategoryFilter: (value: string) => void; clearFilters: () => void; create: () => void; edit: (sport: Deporte) => void; close: () => void; setField: <K extends keyof SportForm>(field: K, value: SportForm[K]) => void; setName: (value: string) => void; save: () => Promise<void>; toggle: (sport: Deporte) => Promise<void>; remove: (sport: Deporte) => Promise<void> }
export const useAdminSportsStore = create<State>((set, get) => ({ sports: [], search: '', filtersOpen: false, statusFilter: 'all', categoryFilter: 'all', editing: null, form: emptyForm, open: false, saving: false, error: '', message: '', load: async () => { try { set({ sports: await adminRepository.fetchSports(), error: '' }) } catch (error) { set({ error: error instanceof Error ? error.message : 'No se pudieron cargar los deportes.' }) } }, setSearch: (search) => set({ search }), toggleFilters: () => set((state) => ({ filtersOpen: !state.filtersOpen })), setStatusFilter: (statusFilter) => set({ statusFilter }), setCategoryFilter: (categoryFilter) => set({ categoryFilter }), clearFilters: () => set({ statusFilter: 'all', categoryFilter: 'all' }), create: () => set({ editing: null, form: emptyForm, error: '', open: true }), edit: (sport) => set({ editing: sport, form: { name: sport.nombre, slug: sport.slug, category: sport.categoria ?? '', players: sport.jugadores_por_equipo?.toString() ?? '', active: sport.activo }, error: '', open: true }), close: () => set({ open: false }), setField: (field, value) => set((state) => ({ form: { ...state.form, [field]: value } })), setName: (name) => set((state) => ({ form: { ...state.form, name, slug: state.editing ? state.form.slug : slugify(name) } })), save: async () => { const { form, editing } = get(); set({ saving: true, error: '', message: '' }); try { await adminRepository.saveSport(editing?.id ?? null, { nombre: form.name.trim(), slug: form.slug.trim() || slugify(form.name), categoria: form.category.trim() || null, jugadores_por_equipo: form.players ? Number(form.players) : null, activo: form.active }); await get().load(); set({ saving: false, open: false, message: editing ? 'Deporte actualizado.' : 'Deporte creado.' }) } catch (error) { set({ saving: false, error: error instanceof Error ? error.message : 'No se pudo guardar el deporte.' }) } }, toggle: async (sport) => { try { await adminRepository.updateSport(sport.id, { activo: !sport.activo }); await get().load(); set({ message: sport.activo ? 'Deporte desactivado.' : 'Deporte reactivado.' }) } catch (error) { set({ error: error instanceof Error ? error.message : 'No se pudo actualizar.' }) } }, remove: async (sport) => { try { await adminRepository.deleteSport(sport.id); await get().load(); set({ message: 'Deporte eliminado definitivamente.' }) } catch (error) { const value = error as { code?: string; message?: string }; set({ error: value.code === '23503' ? 'Este deporte ya esta asociado. Debes desactivarlo.' : value.message ?? 'No se pudo eliminar.' }) } } }))
