import { create } from 'zustand'
import { adminRepository } from '../../services/repositories/adminRepository'
import type { AdminAuditoria, Negocio, SoporteCaso, Usuario } from '../../services/supabase/tables'

export type CaseRow = SoporteCaso & { negocios: { nombre: string } | null; creador: { nombre: string } | null; asignado: { nombre: string } | null }
export type AuditRow = AdminAuditoria & { usuarios: { nombre: string } | null; negocios: { nombre: string } | null }
export type HealthRow = { business: Negocio; courts: number; reservations: number; tournaments: number; subscription: string }
export type SupportForm = { businessId: string; title: string; description: string; priority: string; status: string; assigneeId: string; resolution: string }
const emptyForm: SupportForm = { businessId: '', title: '', description: '', priority: 'media', status: 'abierto', assigneeId: '', resolution: '' }
const failure = (error: unknown) => error instanceof Error ? error.message : 'Operacion no disponible.'
type State = { tab: 'cases' | 'health' | 'audit'; cases: CaseRow[]; audits: AuditRow[]; businesses: Negocio[]; admins: Usuario[]; healthRows: HealthRow[]; search: string; editing: CaseRow | null; form: SupportForm; open: boolean; saving: boolean; error: string; message: string; load: () => Promise<void>; setTab: (value: State['tab']) => void; setSearch: (value: string) => void; create: (adminId: string) => void; createForBusiness: (businessId: string, adminId: string) => void; edit: (item: CaseRow) => void; close: () => void; setField: <K extends keyof SupportForm>(field: K, value: SupportForm[K]) => void; save: (adminId: string) => Promise<void>; remove: (item: CaseRow) => Promise<void> }
export const useAdminSupportStore = create<State>((set, get) => ({ tab: 'cases', cases: [], audits: [], businesses: [], admins: [], healthRows: [], search: '', editing: null, form: emptyForm, open: false, saving: false, error: '', message: '', load: async () => { try { const data = await adminRepository.fetchSupport(); set({ cases: data.cases as unknown as CaseRow[], audits: data.audits as unknown as AuditRow[], businesses: data.businesses, admins: data.admins, healthRows: data.businesses.map((business) => ({ business, courts: data.courts.filter((item) => item.negocio_id === business.id).length, reservations: data.reservations.filter((item) => item.negocio_id === business.id).length, tournaments: data.tournaments.filter((item) => item.negocio_id === business.id).length, subscription: data.subscriptions.find((item) => item.negocio_id === business.id)?.estado ?? 'sin suscripcion' })), error: '' }) } catch (error) { set({ error: failure(error) }) } }, setTab: (tab) => set({ tab }), setSearch: (search) => set({ search }), create: (adminId) => set((state) => ({ editing: null, form: { ...emptyForm, businessId: state.businesses[0]?.id ?? '', assigneeId: adminId }, open: true, error: '' })), createForBusiness: (businessId, adminId) => set({ tab: 'cases', editing: null, form: { ...emptyForm, businessId, assigneeId: adminId }, open: true, error: '' }), edit: (item) => set({ editing: item, form: { businessId: item.negocio_id, title: item.titulo, description: item.descripcion, priority: item.prioridad, status: item.estado, assigneeId: item.asignado_a ?? '', resolution: item.resolucion ?? '' }, open: true, error: '' }), close: () => set({ open: false }), setField: (field, value) => set((state) => ({ form: { ...state.form, [field]: value } })), save: async (adminId) => { const state = get(), form = state.form; if ((form.status === 'resuelto' || form.status === 'cerrado') && !form.resolution.trim()) return set({ error: 'Documenta la resolucion antes de cerrar.' }); set({ saving: true, error: '' }); try { await adminRepository.saveSupportCase(state.editing?.id ?? null, { negocio_id: form.businessId, titulo: form.title.trim(), descripcion: form.description.trim(), prioridad: form.priority, estado: form.status, asignado_a: form.assigneeId || null, resolucion: form.resolution.trim() || null, ...(state.editing ? {} : { creado_por: adminId }) }); await get().load(); set({ saving: false, open: false, message: state.editing ? 'Caso actualizado.' : 'Caso creado.' }) } catch (error) { set({ saving: false, error: failure(error) }) } }, remove: async (item) => { try { await adminRepository.deleteSupportCase(item.id); await get().load(); set({ message: 'Caso eliminado.' }) } catch (error) { set({ error: failure(error) }) } } }))
